"""Added article ratings.

Revision ID: 21ec84874208
Revises: 3d58e8ebf8c6
Create Date: 2020-03-19 01:10:12.194485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ec84874208'
down_revision = '3d58e8ebf8c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('article_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'article_rating')
    # ### end Alembic commands ###
