"""Updated the 'publisher' table.

Revision ID: 39196521adc5
Revises: 07de6afd4745
Create Date: 2019-11-23 05:22:15.997811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39196521adc5'
down_revision = '07de6afd4745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publisher', sa.Column('publ_description', sa.String(length=1000), nullable=True))
    op.add_column('publisher', sa.Column('publ_url', sa.String(length=500), nullable=True))
    op.add_column('publisher', sa.Column('time_created', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('publisher', sa.Column('time_updated', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publisher', 'time_updated')
    op.drop_column('publisher', 'time_created')
    op.drop_column('publisher', 'publ_url')
    op.drop_column('publisher', 'publ_description')
    # ### end Alembic commands ###
