"""Added a seq# for publications.

Revision ID: 3d58e8ebf8c6
Revises: 41cfc117c809
Create Date: 2020-03-18 10:26:25.801673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d58e8ebf8c6'
down_revision = '41cfc117c809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('pub_seqno', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'pub_seqno')
    # ### end Alembic commands ###
