"""Added publication dates.

Revision ID: 41cfc117c809
Revises: 064497c51f2d
Create Date: 2020-01-31 15:02:57.126183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41cfc117c809'
down_revision = '064497c51f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('pub_date', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'pub_date')
    # ### end Alembic commands ###
