"""Allow articles to have a publication date.

Revision ID: 702eeb219037
Revises: a33edb7272a2
Create Date: 2021-11-16 20:41:37.454305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702eeb219037'
down_revision = 'a33edb7272a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('article_date', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'article_date')
    # ### end Alembic commands ###
