export let MAX_IMAGE_UPLOAD_SIZE = ( 1 * 1024*1024 ) ;

export let PUBLISHER_EXCESS_PUBLICATION_THRESHOLD = 5 ;
export let PUBLICATION_EXCESS_ARTICLE_THRESHOLD = 8 ;

export let NEW_ARTICLE_PUB_PRIORITY_CUTOFF = ( 24 * 60 * 60 ) ;
